
export const CATEGORY_TRANSLATION_MAP: Record<string, string> = {
  "womens-dresses": "home.sidebar.womensDresses",
  "mens-shirts": "home.sidebar.mensShirts",
  smartphones: "home.sidebar.smartphones",
  furniture: "home.sidebar.furniture",
  beauty: "home.sidebar.beauty",
  "sports-accessories": "home.sidebar.sportsAccessories",
  vehicle: "home.sidebar.vehicle",
  groceries: "home.sidebar.groceries",
  "skin-care": "home.sidebar.skinCare",
  laptops: "home.sidebar.laptops",
  fragrances: "home.sidebar.fragrances",
  "home-decoration": "home.sidebar.homeDecoration",
  "kitchen-accessories": "home.sidebar.kitchenAccessories",
  tablets: "home.sidebar.tablets",
  "smart-watches": "home.sidebar.smartWatches",
  "mobile-accessories": "home.sidebar.mobileAccessories",
  tops: "home.sidebar.tops",
  "mens-shoes": "home.sidebar.mensShoes",
  "womens-shoes": "home.sidebar.womensShoes",
  "womens-bags": "home.sidebar.womensBags",
  "womens-jewellery": "home.sidebar.womensJewellery",
  sunglasses: "home.sidebar.sunglasses",
  lighting: "home.sidebar.lighting",
  motorcycle: "home.sidebar.motorcycle",
  gaming: "home.sidebar.gaming",
  headphones: "home.sidebar.headphones",
};
